<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Query\Builder;

class Posts extends Model
{
    protected $table = 'posts';
    protected $hidden = [];
    protected $fillable = [
        'title', 'author_id', 'content', 'description'
    ];

    public $timestamps = false;

    /**
     * @link https://learnku.com/articles/3819/learn-the-advanced-part-of-laravel-eloquentorm-with-me
     */
    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        // 按照 title 正序排序
        static::addGlobalScope('title', function (Builder $builder) {
            $builder->orderBy('name', 'asc');
        });
    }
}
